version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "8085:8085"
    env_file:
      - ./Backend/.env
    networks:
      - hireme-network

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - hireme-network

networks:
  hireme-network:
    driver: bridge
